//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.27 at 05:14:45 PM CET 
//


package outputObjects;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatchedOperationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatchedOperationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OutputOperationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InputOperationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OpScore" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="MatchedElement" type="{http://www.kth.se/ict/id2208/Matching}MatchedElementType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatchedOperationType", propOrder = {
    "outputOperationName",
    "inputOperationName",
    "opScore",
    "MatchedElement"
})
public class MatchedOperationType {
	
    @XmlElement(name = "OutputOperationName", required = true)
    protected String outputOperationName;
    @XmlElement(name = "InputOperationName", required = true)
    protected String inputOperationName;
    @XmlElement(name = "OpScore")
    protected String opScore;
    @XmlElement(name = "MatchedElement", required = true)
    protected List<MatchedElementType> MatchedElement;

    /**
     * Gets the value of the outputOperationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputOperationName() {
        return outputOperationName;
    }

    /**
     * Sets the value of the outputOperationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputOperationName(String value) {
        this.outputOperationName = value;
    }

    /**
     * Gets the value of the inputOperationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputOperationName() {
        return inputOperationName;
    }

    /**
     * Sets the value of the inputOperationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputOperationName(String value) {
        this.inputOperationName = value;
    }

    /**
     * Gets the value of the opScore property.
     * 
     */
    public String getOpScore() {
        return opScore;
    }

    /**
     * Sets the value of the opScore property.
     * 
     */
    public void setOpScore(double value) {
    	DecimalFormat numberFormat = new DecimalFormat("#.00");
        this.opScore = numberFormat.format(value);
    }

    /**
     * Gets the value of the MatchedElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the MatchedElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMatchedElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MatchedElementType }
     * 
     * 
     */
    public List<MatchedElementType> getMatchedElement() {
        if (MatchedElement == null) {
            MatchedElement = new ArrayList<MatchedElementType>();
        }
        return this.MatchedElement;
    }

    public void setMatchedElement(List<MatchedElementType> elementList) {
        this.MatchedElement = elementList;
    }
}
